language: python
python:
  - "3.8"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash ./miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda init bash
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda info -a
  - export PYTHONPATH="${PYTHONPATH}:./"


  - conda create -q -n ftl-env python=$TRAVIS_PYTHON_VERSION --file requirements_conda.txt
  - conda activate ftl-env

  - python3 -m pip install -r requirements_pip.txt
script:
  - pytest